// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0xDG__-0eHAwh5Fux_ZEULWGxnGWNBhk',
    appId: '1:991237928883:web:b04aaa4b3ee592ee6fbdc6',
    messagingSenderId: '991237928883',
    projectId: 'optimal-disk-484409-e3',
    authDomain: 'optimal-disk-484409-e3.firebaseapp.com',
    storageBucket: 'optimal-disk-484409-e3.firebasestorage.app',
    measurementId: 'G-3NBB9KJ0W5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2_Taie93Aj6IH5rKt3Y_jFV9DFglrezU',
    appId: '1:991237928883:android:b8266a3b2c9fd76d6fbdc6',
    messagingSenderId: '991237928883',
    projectId: 'optimal-disk-484409-e3',
    storageBucket: 'optimal-disk-484409-e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqSL8EnwJaJWadLMVJteaA9PgGH1gxaR8',
    appId: '1:991237928883:ios:6f19f4c7dc151b816fbdc6',
    messagingSenderId: '991237928883',
    projectId: 'optimal-disk-484409-e3',
    storageBucket: 'optimal-disk-484409-e3.firebasestorage.app',
    iosBundleId: 'com.example.newsWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqSL8EnwJaJWadLMVJteaA9PgGH1gxaR8',
    appId: '1:991237928883:ios:6f19f4c7dc151b816fbdc6',
    messagingSenderId: '991237928883',
    projectId: 'optimal-disk-484409-e3',
    storageBucket: 'optimal-disk-484409-e3.firebasestorage.app',
    iosBundleId: 'com.example.newsWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0xDG__-0eHAwh5Fux_ZEULWGxnGWNBhk',
    appId: '1:991237928883:web:756f8db28563a5aa6fbdc6',
    messagingSenderId: '991237928883',
    projectId: 'optimal-disk-484409-e3',
    authDomain: 'optimal-disk-484409-e3.firebaseapp.com',
    storageBucket: 'optimal-disk-484409-e3.firebasestorage.app',
    measurementId: 'G-WGRHZDWYGE',
  );
}
